"""add row for soft delete and online system

Revision ID: 3729b2a94025
Revises: 8a19c520624e
Create Date: 2026-02-07 13:13:56.437115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3729b2a94025'
down_revision: Union[str, Sequence[str], None] = '8a19c520624e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_groups_is_active'), 'groups', ['is_active'], unique=False)
    op.add_column('posts', sa.Column('create_at', sa.DateTime(), nullable=False))
    op.add_column('posts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_posts_is_active'), 'posts', ['is_active'], unique=False)
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_last_seen'), 'users', ['last_seen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_seen'), table_name='users')
    op.drop_column('users', 'last_seen')
    op.drop_index(op.f('ix_posts_is_active'), table_name='posts')
    op.drop_column('posts', 'is_active')
    op.drop_column('posts', 'create_at')
    op.drop_index(op.f('ix_groups_is_active'), table_name='groups')
    op.drop_column('groups', 'is_active')
    # ### end Alembic commands ###
